apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: confluent-kafka
  description: Confluent Kafka Platfrom
  tags:
    - messaging
    - events
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: cloud-team
  system: events-platfrom
