apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: events-integrity
  description: Check platfrom integrity
  tags:
    - events
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: events-platfrom
