apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customers
  description: The customers API
  tags:
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger Customer
      license:
        name: MIT
    servers:
      - url: http://petstore.swagger.io/v1
    paths:
      /customers:
        get:
          summary: List all customers
          operationId: listCustomers
          tags:
            - customers
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of pets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Customers"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a customer
          operationId: createCustomers
          tags:
            - customers
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /customers/{customerId}:
        get:
          summary: Info for a specific customer
          operationId: showCustomerById
          tags:
            - customers
          parameters:
            - name: customerId
              in: path
              required: true
              description: The id of the customer to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Customer"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Customer:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Customers:
          type: array
          items:
            $ref: "#/components/schemas/Customer"
        Error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
        
