apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: customer-management-portal
  description: Everything related to customers
  tags:
    - portal
spec:
  owner: team-a
  domain: artists
